package HA.Utilities;

import java.util.Properties;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import HA.Properties.HATF_properties;
import HA.Properties.logApp;

public  class MailTrigger {

	public static HATF_properties _properties = new HATF_properties();
	public static String to="",cc="mmulka@innominds.com",subject="",attachmentPath="";

	public static int totalTCcount = 0;
	public static int passTCcount = 0;
	public static int failTCcount = 0;
	public static String testPassPercentage = null;
	public static String testPassRate = null;


	public static void startmail() throws Exception{
		subject="Automation Core Regression Test Suite on Sample_Build Release";
		attachmentPath=MailGeneration.generateMail("Start");
		triggerSendMail();
	}
	
	public static void reportmail() throws Exception{
		subject="Automation Core Regression Test Suite on Sample_Build Release";
		attachmentPath=MailGeneration.generateMail("ExecutionReport");
		triggerSendMail();
	}
	
	public static void failedtcsmail() throws Exception{
		subject="Automation Core Regression Test Suite on Sample_Build Release";
		attachmentPath=MailGeneration.generateMail("failure");
		triggerSendMail();
	}

	public static String exemailtext(){

		String mailtext = "";		
		mailtext=mailtext+"Hi Team,\n";			
		mailtext=mailtext+"We have started executing automation test cases through Selenium. We'll be receiving another results e-mail when execution is complete.\n";			
		mailtext=mailtext+"Note: This is automatically generated by automation tool.\n";			
		mailtext=mailtext+"Regards\n";
		mailtext=mailtext+"Automation Team";		
		return mailtext;		
	}


	public static void triggerSendMail()
	{
		final String userName="QAautomationrun@hostanalytics.com";
		final String passWord= "automation@123";
		String host="smtp.gmail.com";
		String port="465";
		String starttls="true";
		String auth="true";
		boolean debug=true;
		String socketFactoryClass="javax.net.ssl.SSLSocketFactory";
		String fallback="false";


		//Object Instantiation of a properties file.
		Properties props = new Properties();
		props.put("mail.smtp.user", userName);
		props.put("mail.smtp.host", host);


		if(!"".equals(port)){
			props.put("mail.smtp.port", port);
		}

		if(!"".equals(starttls)){
			props.put("mail.smtp.starttls.enable",starttls);
			props.put("mail.smtp.auth", auth);
		}

		if(debug){
			props.put("mail.smtp.debug", "true");
		}
		else{
			props.put("mail.smtp.debug", "false");
		}

		if(!"".equals(port)){
			props.put("mail.smtp.socketFactory.port", port);
		}

		if(!"".equals(socketFactoryClass)){
			props.put("mail.smtp.socketFactory.class",socketFactoryClass);
		}

		if(!"".equals(fallback)){
			props.put("mail.smtp.socketFactory.fallback", fallback);
		}

		try{
			// Get the Session object.
			Session session = Session.getInstance(props, new javax.mail.Authenticator() {
				protected PasswordAuthentication getPasswordAuthentication() {
					return new PasswordAuthentication(userName, passWord);
				}
			});
			//Session session = Session.getDefaultInstance(props, null);
			MimeMessage msg = new MimeMessage(session);
			msg.setSubject(subject);
			Multipart multipart = new MimeMultipart();
			MimeBodyPart messageBodyPart = new MimeBodyPart();
			DataSource source = new FileDataSource(attachmentPath);
			messageBodyPart.setDataHandler(new DataHandler(source));
			multipart.addBodyPart(messageBodyPart);
			msg.setContent(multipart);
			msg.setFrom(new InternetAddress(userName));

			msg.addRecipients(Message.RecipientType.TO, to);
			msg.addRecipients(Message.RecipientType.CC, cc);
			msg.saveChanges();
			Transport transport = session.getTransport("smtp");
			transport.connect(host, userName, passWord);
			logApp.logger.info("Mail Connected");
			System.out.println("Mail Connected");

			transport.sendMessage(msg, msg.getAllRecipients());
			transport.close();
			logApp.logger.info("Mail Sent");
			System.out.println("Mail Sent");
		} 

		catch (Exception e){
			e.printStackTrace();
			logApp.logger.error(e);				
		}
	}

}
